### PR TITLE
This isn't nearly fucking everything but it's a start.

### PR DESCRIPTION
**Pull request by TheLumaio**
Seriously, learn to code before doing shit like this. I nearly cried yo.

### CODE REVIEW

**Comment by TheLumaio** [comment]
also 16:9 resolutions are janky af, fix that unless you wanna be stuck in 1997

**Comment by Verideth** [comment]
I like my code, besides, your "changes" are mostly just coding style changes, I haven't read thru all of it. But it doesn't look needed.

**Comment by TheLumaio** [comment]
👍 you clearly didn't look at all of it but here, how bout i just list everything you did wrong?

- global variables
- extern (never use this, seriously)
- you put camera matrices inside the gamemanager class when you could have just shoved it in the camera class and called it a day
- global variables
- you put your event callbacks outside the gamemanager class
- your_function_naming_scheme_is_dumb
- global variables

**Comment by TheLumaio** [comment]
global variables is the big one, no one will ever take you seriously as a coder if you use global variables

**Comment by TheLumaio** [comment]
I didn't even mention that you're using deprecated opengl functions

**Pull request closed without merging**
